[package]
name = "ndarray-numtest"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
ndarray = "0.7"
rand = "0.3"
float-cmp = "0.2"
num = "0.1.35"

[dev-dependencies]
ndarray-rand = "0.3"
