[package]
name = "ndarray-numtest"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
ndarray = "0.7"
rand = "*"
ndarray-rand = "*"
float-cmp = "0.2"
num-traits = "*"
